/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestCore;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    
    @Test void returnTrueTest() {
    	assertTrue(true);
    }
    
//    @Test void returnFalseTest() {
//    	assertTrue(false);
//    }
}
